# docker-compose.yml
version: '3.8'

services:
  frontend-nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npx nuxt dev